#!/usr/bin/bash

# variables
config=/home/wrq/.config/hypr
scripts=/home/wrq/.config/hypr/scripts

export PATH="$PATH:/opt/go/bin:/home/wrq/_install/swww/target/release"

# wallpaper
$scripts/wall $config/wallpapers/caoyuan.jpg &

# notification daemon
dunst &

blueman-applet &
# light and sleep
#swayidle -w \
#	timeout 600 'bash ~/.cache/swayidle/save_backup_light.sh' \
#	resume 'bash ~/.cache/swayidle/set_backup_light.sh' \
#	timeout 1800 'sudo systemctl suspend' \
#	before-sleep 'swaylock -f -c 000000' &

# waybar
/home/wrq/.config/hypr/scripts/launch_waybar &
nm-applet &

#$scripts/tools/dynamic &

#ewwbar
#/home/wrq/.config/hypr/scripts/launch_ewwbar &

/usr/local/libexec/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
