#!/usr/bin/bash

is_active=$(pgrep wlsunset)

toggle() {
    if [[ -n $is_active ]]; then
        pkill wlsunset
    else
        wlsunset -T 3501 -t 3500 &
    fi
}

icon() {
    if [[ -n $is_active ]]; then
        echo "󰛨"
        exit 1
    else
        echo "󰹏"
        exit 1
    fi
}

status() {
    if [[ -n $is_active ]]; then
        echo "Turned on"
        exit 1
    else
        echo "Turned off"
        exit 1
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi